### PR TITLE
SPI GenServer uses handle_info instead of receive

### PR DESCRIPTION
**Pull request by sandromehic**
Solves the concurrent reads reported in #53

### CODE REVIEW

**Comment by sandromehic** [comment]
Some improvements might be a delay to the loop that keeps calling the `GenServer` when it return `:busy`, I don't know if that would change much performance wise.

Btw, I have tested this code live on my RPi3 Board with MCP3008 ADC. I haven't included these tests in the PR since they are board and device dependant. Maybe I could write up two tests with some mocks to have some generic tests. These are the tests that could be used as a starting point:

```elixir
defmodule Integration.ConcurrentReadsTest do
  use ExUnit.Case

  @n 7

  @tag device: true
  test "sequential read :ok" do
    read =
      0..@n
      |> Enum.map(fn x -> transfer(x) end)

    assert read |> ok? == expected(@n, :ok)
  end

  @tag device: true
  test "concurrent read :ok" do
    read =
      0..@n
      |> Enum.map(&task/1)
      |> Enum.map(&Task.await/1)

    assert read |> ok? == expected(@n, :ok)
  end

  @doc """
  Convert from a list of positive numbers to a list of `:ok`.

  If any of the elements is not a positive number, returns false.
  """
  def ok?([head | tail]) when head >= 0 do
    [:ok | ok?(tail)]
  end

  def ok?([]), do: []
  def ok?(_), do: false

  def expected(n, term) do
    0..n |> Enum.map(fn _ -> term end)
  end

  def transfer(n) do
    Example.SPIRead.MCP3008.channel(n)
  end

  def task(n), do: Task.async(fn -> transfer(n) end)
end
```

**Comment by fhunleth** [comment]
Thanks for getting this going!

I don't like that this solution busy loops between the `transfer` and `handle_call` when a request is being processed and also that there's no timeout. It would be better to block. I suppose that you could do this by queuing requests in the GenServer state instead of holding just one. My problem with that solution is that it seems to obfuscating the code when you add in handling for requester processes crashing and timing out. Plus we get the process mailbox queue "for free" so it doesn't feel right to create another queue. If you put the `receive` block back and fix the issue with the `receive` block handling `_` by making it only handle events from the port, I think that we'll have a solution that blocks callers when a request is outstanding without making the code much more complicated. I'm on the fence as to whether the C code should perform the retries or Elixir. I suppose that either is fine, so if you add a limited number of retries, I'd be good with it.

**Comment by axelson** [comment]
Would it make sense/be cleaner to introduce an intermediate GenServer that simply serializes the requests?

**Comment by sandromehic** [comment]
@axelson I don't think making another GenServer would fix the issue. It's the offending `receive` block that should not interfere with any GenServer calls so moving it to another one does not solve the issue.

@fhunleth Your doubts have actually helped me identify the problem better. Instead of the solution I propose in the PR, a simpler way would be to move the `receive` block to its own process and wait for its reply. An example implementation might be this:

```elixir
  defp call_port(state, command, arguments) do
    task = Task.async(fn ->
      receive do
        {_, {:data, response}} ->
          {:ok, :erlang.binary_to_term(response)}

        _ ->
          :error
      end
    end)

    msg = {command, arguments}
    send(state.port, {task.pid, {:command, :erlang.term_to_binary(msg)}})
    Task.await(task)
  end
```

If you think this type of solution might be the way to go, I can work on it. Also I could add some testing for this issue, but it would include some refactoring, maybe I'll work on an additional commit that you can chose to include or not.

**Comment by fhunleth** [comment]
@sandromehic The reply message from the port won't get sent to the Task. You may also be interested in the implementation of `await/2`, though, since it's just a `receive` block. See https://github.com/elixir-lang/elixir/blob/v1.6.1/lib/elixir/lib/task.ex#L480-L493. Anyway, my suggestion is just to stick with the current `receive` loop, but remove the `_` catchall. If I were writing this now, I'd add a timeout. Then I'd add the retry on busy and refactor it to look nice.

p.s. I'm thrilled that you're thinking of testing. This project was the first thing that I wrote in Elixir and I had no clue. I'm in the process of getting an `elixir_ale` 2.0 started that can take advantage of Erlang and Linux features that weren't around when I first wrote this. If it's not easy to get the test in here, don't worry about it. I'll revisit for 2.0.

**Comment by adkron** [comment]
I'd be willing to pair on some testing for this if someone is interested.

**Comment by sandromehic** [comment]
@fhunleth I wasn't aware of the `Task.await/2` implementation, thanks for pointing it out. At this point it seems like the simplest solution is the one you propose, to remove the `_` catchall inside `receive`. This way, it doesn't intercept GenServer messages, and there is no need for all the `handle_info` callback that I proposed.

The only thing left to decide is if you would like to introduce a configurable timeout or just stick with the GenServers default (5000 ms). If we keep the default one, we can just remove the `_` catchall and thats it. Otherwise the timeout configuration should be held someplace, I'm not sure if there is a better place or should this be in the `GenServer` state?

The fix at this point could be just this line of code. Let me know if you also would like to have timeout configuration.

```elixir
       {_, {:data, response}} ->
         {:ok, :erlang.binary_to_term(response)}
 
-      _ ->
+      {:EXIT, _port, _reason} ->
         :error
```

edit: I could not change the branch for the pull request, so I might create a new one, or you can just create a new commit yourself with this change, so we don't create another pull request.

**Comment by adkron** [comment]
I added #56 to take care of the first issue with tests. @sandromehic, would you mind updating to add handling the actual exit call? We should probably return the `{:error, reason}`. If you need help with testing I would be happy to pair on it. I was really wanting to get in the port behaviour to make testing work by allowing us to inject responses. Let me know what you think.

**Comment by fhunleth** [comment]
Late to responding here, but I'll get the receive fix in later tonight and we can go from there.

**Comment by fhunleth** [comment]
I merged the receive fix in, added a timeout, and started returning errors from the port. @sandromehic I took your example program and updated it to run 32 requests concurrently and everything seems to work fine for me on a Raspberry Pi 3 w/ Nerves and 5370261283492682a3949709a630c157fac353a8. If you point your dependency to `master`, you'll get the changes. Could you verify that they work for you?

I also applied your change to the I2C and GPIO code since they suffered from the same issue. I'll verify those. Don't worry about closing this PR. I'll clean everything up once I know that the code is in a good place. Thanks again!

**Comment by sandromehic** [comment]
@adkron This pull request is actually outdated, since we found a better solution. The testing that you provide is nice, lets see with @fhunleth if he wants to include some mocks now or wait for the 2.0 release.
@fhunleth Thanks for taking care of the issue and merging the fixes upstream. Today I'm in a different office so I don't have the RPi3 board with me, I will confirm if it works tomorrow.

**Comment by fhunleth** [comment]
@sandromehic Thanks for testing it out. I'm pretty sure that it will work for you, but it's good to have confirmation.

@adkron I'm very interested in improving the testability of ElixirALE and programs that use it. Let's continue the conversation in issue #55 when you get done with ElixirDaze. Also, while our initial goal with 2.0 was to keep the ElixirALE API pretty close to 1.0, I'm open to more radical API changes if there's a more elegant way of making the library friendlier to testing. Just something to keep in mind.

**Comment by sandromehic** [comment]
@fhunleth Just tested with master branch. All my tests for concurrent reads pass. Thanks for the availability to solve this issue quickly. I think we can close this issue now :smile:

**Comment by fhunleth** [comment]
v1.0.3 released with the fix.

**Pull request closed without merging**
