### PR TITLE
Increase I2C buffer size from 32 to 512 bytes

### PR DESCRIPTION
**Pull request by artob**
As discussed in #20.

### CODE REVIEW

**Comment by artob** [comment]
Note 69c732ad39d50fb8c0747c795cb81b7262bfa181. We may want some safer long-term solution here, as the causal dependency between the max I2C buffer size and the EI response buffer size isn't readily evident at present to someone casually perusing the code (or increasing the I2C buffer size, going forward).

**Comment by fhunleth** [comment]
Thanks! The changes look good, and I agree that it would be nice to have a better solution. At some point, I'd like to revisit the Erlang term parsing in all of my projects since it has a number of deficiencies. However, I think that your change will suffice for a quite a while.

erlang_ale doesn't get many changes, so I'm going to push a release up to hex with your change so that it's available to others. Ping me in the next couple days if you run into issues.

**Comment by artob** [comment]
Thanks for merging, @fhunleth!

**Comment by artob** [comment]
@fhunleth, when you have a chance, could you push out 0.5.6 to Hex.pm, please?

**Comment by fhunleth** [comment]
@bendiken: Published!

**Comment by artob** [comment]
Thanks!

**Pull request merged**
