### PR TITLE
Add `pin/1` to GPIO for getting the linked GPIO PIN number

### PR DESCRIPTION
**Pull request by jjcarstens**
This is just a really simple helper function to get the `pin` that is associated with the GPIO GenServer process.

Lately I've found myself with a list of GenServer processes wonder what pin it is using so thought I'd add here in case any other folks fall in the same predicament 😆

### CODE REVIEW

**Comment by fhunleth** [comment]
That does sound helpful! I'll take a look tonight.

@mattludwigs @mdsebald - Could one of you look into adding this to `ElixirCircuits.GPIO` so that it will be available there as well?

**Review by adkron — APPROVED** [review]
I have also thought about this and used other means to get to it. I think this is a nice addition.

**Comment by mdsebald** [comment]
I'll take a look.

**Comment by fhunleth** [comment]
There was a conflict, so I manually resolved it: https://github.com/fhunleth/elixir_ale/commit/9e3cb201ab848c9543ba71c09c09c44eac4b7658

I also made a new release. It's in v1.2.0.

**Pull request closed without merging**
