### PR TITLE
Increases usleep timeout after first failure to read direction file.

### PR DESCRIPTION
**Pull request by CoderDennis**
Thanks for the answer on slack! I figured I would go ahead and submit the change since it fixed the problem for me.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks for investigating this and sending the pull request! I was thinking about this problem and wondering if the delay might need to be even longer if the system is under load when the GPIO is initialized. What do you think about polling like this: https://github.com/fhunleth/elixir_ale/tree/CoderDennis-master? I'm a little worried that I might be pulling PRs to make the timeout longer in the future, and this would seem to fix that. Anyway, I'm curious on your thoughts, and I don't have a Pi 2 handy to test, so if you're in a good spot to try it out, that would help.

**Comment by CoderDennis** [comment]
I like the polling idea. Was thinking that was a good idea, but I'm not confident enough in C to try it. Was this also an issue on earlier Pi versions? I also have the previous gen Pi B+ from 2014. I should be able to test it there also.

**Comment by fhunleth** [comment]
The original timeout was put in when I was using a Raspberry Pi A+. I can't imagine it being different on a B+, but it would be great if you could check it there too. Thanks!

**Comment by CoderDennis** [comment]
Polling works great on Pi 2. The only thing that's a little annoying is that when running in iex, you see the error message a whole bunch of times. Even with the 50000 timeout, the error message was displayed once. Could we suppress the error message? Maybe only show it if DEBUG is defined. Or only show it if we exhaust the retries.

Polling also works on Pi B+, but it looks like it goes through more retries. Nowhere near the full 1000 though, so I think we're good.

**Comment by fhunleth** [comment]
Good point. This is what I get for being lazy and not breaking out hardware to test the change. You're right, nothing should be printed if the GPIO initializes successfully, so I converted those warnings to debug prints, and also added an error message on any gpio_init failure (shocking that it was missing). I pushed the change to GitHub. As penance, I'll get an RPi and test it out this weekend or Monday evening to make sure it works. Thanks for trying it out.

**Comment by CoderDennis** [comment]
I think what you have in the CoderDennis-master branch is better than what I had in this pull request.

**Comment by fhunleth** [comment]
I just wanted to let you know that I finally was able to test the changes to make sure that everything work on my RPi. I pushed a new version (0.4.0) to hex.pm with the retries. Thanks again for letting me know about this issue.

**Pull request closed without merging**
